### ISSUE TITLE
В чём смысл этой строки?

### ISSUE THREAD

**Issue by coursar** [sunatullo-gafurov/DOM-up-down#5]
https://github.com/sunatullo-gafurov/DOM-up-down/blob/7fdd56d56943fefcee34e3e25abd0ad10fbd434e/src/js/app.js#L43

**Comment by coursar** [comment]
Какой default action у кнопки по умолчанию?

**Comment by sunatullo-gafurov** [comment]
Если e.preventDefault(); не ставим то страница обновляется когда нажимаем верхнюю конпку.

**Comment by coursar** [comment]
Обновляется она по одной простой причине - вы неправильно сформировали структуру страницы. В итоге ваша кнопка попала в форму, т.к. вместо закрывающего тега `form` вы написали снова его же.

В ошибках нужно разбираться и выяснять, почему не работает, а не вешать "костыли" на свой код.

**Comment by coursar** [comment]
```html
    <form>
        <label><h3>Total</h3></label>
        <input data-input="input-total" class="form-control" type="number" min="0" value="">
        <label><h3>Category</h3></label>
        <input data-input="input-category"class="form-control" type="text" value="">
        <button data-action="add-button"type="submit" class="btn btn-success btn-block margin-top">Add</button>
    <form>
```;

На последней строке ничего не смущает?
