### ISSUE TITLE
В какой из лекций рекомендовалось использовать Node вместо Element?

### ISSUE THREAD

**Issue by coursar** [sunatullo-gafurov/DOM-up-down#7]
https://github.com/sunatullo-gafurov/DOM-up-down/blob/7fdd56d56943fefcee34e3e25abd0ad10fbd434e/src/js/app.js#L44

**Comment by sunatullo-gafurov** [comment]
В седьмой лекции

**Comment by coursar** [comment]
<img width="766" alt="Снимок экрана 2020-02-01 в 4 11 40" src="https://user-images.githubusercontent.com/3601892/73580856-fdb65180-44a8-11ea-996c-3aa8397d995d.png">

Вы точно читали 7-ую лекцию? На 27-ом слайде там написано вот так.
